# Hello! Thank you for downloading my plugin!
# This is an up-to-date version of PermissionsExTabColors since the author has abandoned his version
# The plugin works the same way and was re-developed for 1.8+